import type { RateCardEntry } from "./schemas";

/**
 * Seed rate card, mined from all 76 sheets of `_reference/Royal - March.xlsx`.
 * `defaultRate` is the observed "typical" figure; `minRate`/`maxRate` bound
 * the admin's rate-master editor. All are ADMIN-EDITABLE after seeding —
 * these are starting values, not hardcoded prices.
 */

const PROFILE_OPTIONS = ["BAYDEE (Half white)", "GT / Galaxy Trader (Milk white)", "Green Tech", "Fenstech", "Eroline"];
const GLASS_OPTIONS = [
  "Clear or pinned",
  "Pinned glass",
  "Frosted",
  "Golden tinted",
  "One way (blue)",
  "One way (brown)",
  "One way (golden)",
  "One way (green)",
  "5mm toughened",
  "6mm toughened",
  "8mm toughened",
  "12mm toughened",
  "Design glass",
];
const MESH_OPTIONS = ["Aluminium mesh (standard)", "SS mesh (+₹20/sqft)", "No mesh"];
const COLOUR_OPTIONS = ["White", "Half white", "Milk white", "Teak color", "Brown", "Golden Oak"];

export const RATE_CARD_SEED: Omit<RateCardEntry, "_id">[] = [
  // ---- sliding windows ----
  {
    productType: "sliding_2_track",
    label: "2 Track sliding window",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 300,
    minRate: 270,
    maxRate: 350,
    diagramType: "sliding_2_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "sliding_2_track_teak",
    label: "2 Track sliding window (Teak color)",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 550,
    minRate: 550,
    maxRate: 550,
    diagramType: "sliding_2_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "sliding_2_5_track",
    label: "2.5 Track sliding window",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 355,
    minRate: 330,
    maxRate: 380,
    diagramType: "sliding_2_5_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "sliding_2_5_track_mesh",
    label: "2.5 Track sliding window with fly mesh",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 355,
    minRate: 310,
    maxRate: 370,
    diagramType: "sliding_2_5_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "sliding_3_track",
    label: "3 Track sliding window",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 355,
    minRate: 320,
    maxRate: 450,
    diagramType: "sliding_3_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "sliding_3_track_mesh",
    label: "3 Track sliding window with fly mesh",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 400,
    minRate: 360,
    maxRate: 500,
    diagramType: "sliding_3_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "sliding_vertical",
    label: "2 Track vertical sliding window",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 450,
    minRate: 450,
    maxRate: 450,
    diagramType: "sliding_vertical",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  // ---- balcony (first-class category in their own vocabulary) ----
  {
    productType: "balcony_window",
    label: "Balcony window",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 360,
    minRate: 320,
    maxRate: 400,
    diagramType: "sliding_2_5_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "balcony_window_toughened",
    label: "Balcony window (8mm toughened glass, white)",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 550,
    minRate: 450,
    maxRate: 650,
    diagramType: "sliding_2_5_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "balcony_golden_oak_92_sash",
    label: "Balcony window, 3 Track 92 sash (Golden Oak, 8mm toughened)",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 900,
    minRate: 900,
    maxRate: 900,
    diagramType: "sliding_3_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  // ---- casement / fixed ----
  {
    productType: "fixed_window",
    label: "Fixed window",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 310,
    minRate: 290,
    maxRate: 340,
    diagramType: "fixed",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "fixed_window_per_piece",
    label: "Fixed window (small, priced per piece)",
    category: "casement_fixed",
    pricingMode: "per_unit",
    defaultRate: 1800,
    minRate: 1200,
    maxRate: 2500,
    diagramType: "fixed",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "openable_window",
    label: "Openable window",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 450,
    minRate: 400,
    maxRate: 500,
    diagramType: "casement",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "top_openable_fixed",
    label: "Top openable & fixed window",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 460,
    minRate: 450,
    maxRate: 475,
    diagramType: "combination",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  // ---- ventilators (mostly per-piece) ----
  {
    productType: "ventilator",
    label: "Ventilator",
    category: "ventilator",
    pricingMode: "per_unit",
    defaultRate: 1700,
    minRate: 1200,
    maxRate: 2000,
    diagramType: "ventilator",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "ventilator_fan_point",
    label: "Ventilator with fan point",
    category: "ventilator",
    pricingMode: "per_unit",
    defaultRate: 1800,
    minRate: 1000,
    maxRate: 2000,
    diagramType: "ventilator",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "ventilator_louver_mesh",
    label: "Ventilator with louvers & mesh",
    category: "ventilator",
    pricingMode: "per_unit",
    defaultRate: 1600,
    minRate: 1600,
    maxRate: 1600,
    diagramType: "louver",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  // ---- doors ----
  {
    productType: "sliding_door_upvc",
    label: "uPVC sliding door",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 350,
    minRate: 350,
    maxRate: 350,
    diagramType: "sliding_door",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "openable_door",
    label: "Openable door",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 550,
    minRate: 450,
    maxRate: 670,
    diagramType: "french_door",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "office_door_glass",
    label: "Office door (openable with glass)",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 650,
    minRate: 630,
    maxRate: 650,
    diagramType: "french_door",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "wpc_flush_door",
    label: "WPC / flush door",
    category: "door",
    pricingMode: "per_unit",
    defaultRate: 4000,
    minRate: 4000,
    maxRate: 15000,
    diagramType: "flush_door",
    specOptions: { profiles: ["WPC"], colours: ["Teak", "Walnut", "White"], glass: [], mesh: [] },
    active: true,
  },
  {
    productType: "bathroom_door",
    label: "Bathroom / washroom door (uPVC panel)",
    category: "door",
    pricingMode: "per_unit",
    defaultRate: 2500,
    minRate: 2300,
    maxRate: 2500,
    diagramType: "bathroom_door",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: [], mesh: [] },
    active: true,
  },
  // ---- mesh & aluminium ----
  {
    productType: "mesh_shutter_3track",
    label: "3 Track mesh shutter",
    category: "mesh",
    pricingMode: "per_sqft",
    defaultRate: 250,
    minRate: 250,
    maxRate: 250,
    diagramType: "mesh_standalone",
    specOptions: { profiles: [], colours: [], glass: [], mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "mesh_plated_foldable",
    label: "Plated / foldable mesh",
    category: "mesh",
    pricingMode: "per_sqft",
    defaultRate: 300,
    minRate: 270,
    maxRate: 320,
    diagramType: "mesh_standalone",
    specOptions: { profiles: [], colours: [], glass: [], mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "mesh_pleated_acrylic",
    label: "Pleated mesh (Acrylic)",
    category: "mesh",
    pricingMode: "per_sqft",
    defaultRate: 750,
    minRate: 750,
    maxRate: 750,
    diagramType: "mesh_standalone",
    specOptions: { profiles: [], colours: [], glass: [], mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "aluminium_window",
    label: "Aluminium window",
    category: "aluminium",
    pricingMode: "per_sqft",
    defaultRate: 320,
    minRate: 280,
    maxRate: 400,
    diagramType: "aluminium_window",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "aluminium_sliding_door",
    label: "Aluminium sliding door",
    category: "aluminium",
    pricingMode: "per_sqft",
    defaultRate: 450,
    minRate: 450,
    maxRate: 450,
    diagramType: "aluminium_sliding",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  // ---- vernacular / job-specific (from the Agrahara Lyt workbook) ----
  {
    productType: "sajja",
    label: "Sajja",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 270,
    minRate: 270,
    maxRate: 270,
    diagramType: "fixed",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "kitchen_sajja",
    label: "Kitchen / Kitchen sajja",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 400,
    minRate: 400,
    maxRate: 400,
    diagramType: "fixed",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "glass_only_toughened",
    label: "Glass only, 12mm toughened",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 160,
    minRate: 160,
    maxRate: 160,
    diagramType: "fixed",
    specOptions: { profiles: [], colours: [], glass: ["12mm toughened"], mesh: [] },
    active: true,
  },
];
