import type { RateCardEntry } from "./schemas";

/**
 * Seed rate card, mined from all 76 sheets of `_reference/Royal - March.xlsx`.
 * `defaultRate` is the observed "typical" figure; `minRate`/`maxRate` bound
 * the admin's rate-master editor. All are ADMIN-EDITABLE after seeding —
 * these are starting values, not hardcoded prices.
 */

const PROFILE_OPTIONS = ["BAYDEE (Half white)", "GT / Galaxy Trader (Milk white)", "Green Tech", "Fenstech", "Eroline"];
const GLASS_OPTIONS = [
  "Clear glass",
  "Clear or pinned",
  "Pinned glass",
  "Frosted",
  "Golden tinted",
  "One way (blue)",
  "One way (brown)",
  "One way (golden)",
  "One way (green)",
  "5mm toughened",
  "6mm toughened",
  "8mm toughened",
  "12mm toughened",
  "Design glass",
];
const MESH_OPTIONS = ["Aluminium mesh (standard)", "SS mesh (+₹20/sqft)", "No mesh"];
// Priced colours first (see lib/pricing.ts's COLOR_SURCHARGES,
// colorPerSqftSurcharge, colorFlatSurcharge — these exact string values are
// what the pricing rules match on): Black/Gray/Brown add a flat surcharge,
// Golden Oak/Walnut/Mahogany ("wood-tone") double the item's own rate.
// Unpriced colours kept after, in their original order.
const COLOUR_OPTIONS = ["Black", "Gray", "Brown", "Golden Oak", "Walnut", "Mahogany", "White", "Half white", "Milk white", "Teak"];

export const RATE_CARD_SEED: Omit<RateCardEntry, "_id">[] = [
  // ---- sliding windows ----
  {
    productType: "sliding_2_track",
    label: "2 Track sliding window",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 300,
    minRate: 270,
    maxRate: 350,
    diagramType: "sliding_2_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "sliding_2_track_teak",
    label: "2 Track sliding window (Teak colour)",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 550,
    minRate: 550,
    maxRate: 550,
    diagramType: "sliding_2_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "sliding_2_5_track",
    label: "2.5 Track sliding window",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 355,
    minRate: 330,
    maxRate: 380,
    diagramType: "sliding_2_5_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "sliding_2_5_track_mesh",
    label: "2.5 Track sliding window with fly mesh",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 355,
    minRate: 310,
    maxRate: 370,
    diagramType: "sliding_2_5_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "sliding_3_track",
    label: "3 Track sliding window",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 355,
    minRate: 320,
    maxRate: 450,
    diagramType: "sliding_3_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "sliding_3_track_mesh",
    label: "3 Track sliding window with fly mesh",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 400,
    minRate: 360,
    maxRate: 500,
    diagramType: "sliding_3_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "sliding_vertical",
    label: "2 Track vertical sliding window",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 450,
    minRate: 450,
    maxRate: 450,
    diagramType: "sliding_vertical",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  // ---- balcony (first-class category in their own vocabulary) ----
  {
    productType: "balcony_window",
    label: "Balcony window",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 360,
    minRate: 320,
    maxRate: 400,
    diagramType: "sliding_2_5_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "balcony_window_toughened",
    label: "Balcony window (white, 8mm toughened glass)",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 550,
    minRate: 450,
    maxRate: 650,
    diagramType: "sliding_2_5_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "balcony_golden_oak_92_sash",
    label: "Balcony window — 3 Track, 92 sash (Golden Oak, 8mm toughened)",
    category: "sliding",
    pricingMode: "per_sqft",
    defaultRate: 900,
    minRate: 900,
    maxRate: 900,
    diagramType: "sliding_3_track",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  // ---- casement / fixed ----
  {
    productType: "fixed_window",
    label: "Fixed window",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 310,
    minRate: 290,
    maxRate: 340,
    diagramType: "fixed",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "fixed_window_per_piece",
    label: "Fixed window (small)",
    category: "casement_fixed",
    pricingMode: "per_unit",
    defaultRate: 1800,
    minRate: 1200,
    maxRate: 2500,
    diagramType: "fixed",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "openable_window",
    label: "Openable window",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 450,
    minRate: 400,
    maxRate: 500,
    diagramType: "casement",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "top_openable_fixed",
    label: "Top openable and fixed window",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 460,
    minRate: 450,
    maxRate: 475,
    diagramType: "combination",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  // ---- ventilators (mostly per-piece) ----
  {
    productType: "ventilator",
    label: "Ventilator",
    category: "ventilator",
    pricingMode: "per_unit",
    defaultRate: 1700,
    minRate: 1200,
    maxRate: 2000,
    diagramType: "ventilator",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "ventilator_fan_point",
    label: "Ventilator with fan point",
    category: "ventilator",
    pricingMode: "per_unit",
    defaultRate: 1800,
    minRate: 1000,
    maxRate: 2000,
    diagramType: "ventilator",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "ventilator_louver_mesh",
    label: "Ventilator with louvres and mesh",
    category: "ventilator",
    pricingMode: "per_unit",
    defaultRate: 1600,
    minRate: 1600,
    maxRate: 1600,
    diagramType: "louver",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  // ---- doors ----
  {
    productType: "sliding_door_upvc",
    label: "uPVC sliding door",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 350,
    minRate: 350,
    maxRate: 350,
    diagramType: "sliding_door",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "openable_door",
    label: "Openable door",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 550,
    minRate: 450,
    maxRate: 670,
    diagramType: "openable_door_single",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "office_door_glass",
    label: "Office door (glazed, openable)",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 650,
    minRate: 630,
    maxRate: 650,
    diagramType: "openable_door_double",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "wpc_flush_door",
    label: "WPC",
    category: "door",
    pricingMode: "per_unit",
    defaultRate: 4000,
    minRate: 4000,
    maxRate: 15000,
    diagramType: "flush_door",
    specOptions: { profiles: ["WPC"], colours: ["Teak", "Walnut", "White"], glass: [], mesh: [] },
    active: true,
  },
  {
    productType: "bathroom_door",
    label: "Bathroom door (uPVC panel)",
    category: "door",
    pricingMode: "per_unit",
    defaultRate: 2500,
    minRate: 2300,
    maxRate: 2500,
    diagramType: "bathroom_door",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: [], mesh: [] },
    active: true,
  },
  // ---- mesh & aluminium ----
  {
    productType: "mesh_shutter_3track",
    label: "3 Track mesh shutter",
    category: "mesh",
    pricingMode: "per_sqft",
    defaultRate: 250,
    minRate: 250,
    maxRate: 250,
    diagramType: "mesh_standalone",
    specOptions: { profiles: [], colours: [], glass: [], mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "mesh_plated_foldable",
    label: "Pleated / foldable mesh",
    category: "mesh",
    pricingMode: "per_sqft",
    defaultRate: 300,
    minRate: 270,
    maxRate: 320,
    diagramType: "mesh_standalone",
    specOptions: { profiles: [], colours: [], glass: [], mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "mesh_pleated_acrylic",
    label: "Pleated mesh (Acrylic)",
    category: "mesh",
    pricingMode: "per_sqft",
    defaultRate: 750,
    minRate: 750,
    maxRate: 750,
    diagramType: "mesh_standalone",
    specOptions: { profiles: [], colours: [], glass: [], mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "aluminium_window",
    label: "Aluminium window",
    category: "aluminium",
    pricingMode: "per_sqft",
    defaultRate: 320,
    minRate: 280,
    maxRate: 400,
    diagramType: "aluminium_window",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "aluminium_sliding_door",
    label: "Aluminium sliding door",
    category: "aluminium",
    pricingMode: "per_sqft",
    defaultRate: 450,
    minRate: 450,
    maxRate: 450,
    diagramType: "aluminium_sliding",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  // The "Sajja" / "Kitchen sajja" entries transcribed from the Agrahara Lyt
  // workbook were removed at the client's instruction — vernacular job-sheet
  // shorthand that doesn't belong on a customer-facing quotation. Nothing in
  // the app referenced them beyond this seed file.
  {
    productType: "glass_only_toughened",
    label: "Toughened glass only (12mm)",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 160,
    minRate: 160,
    maxRate: 160,
    diagramType: "fixed",
    specOptions: { profiles: [], colours: [], glass: ["12mm toughened"], mesh: [] },
    active: true,
  },

  // ---- aluminium range — mined from the client's handwritten rate sheet,
  // rates confirmed directly with the client (see docs/archive/FUTURE-IDEAS.md's
  // "Rate card additions" entry for the source and every confirmed number) ----
  {
    productType: "aluminium_sliding_2_track",
    label: "Aluminium 2 Track sliding window",
    category: "aluminium",
    pricingMode: "per_sqft",
    defaultRate: 325,
    minRate: 300,
    maxRate: 350,
    diagramType: "sliding_2_track",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "aluminium_sliding_3_track",
    label: "Aluminium 3 Track sliding window",
    category: "aluminium",
    pricingMode: "per_sqft",
    defaultRate: 425,
    minRate: 400,
    maxRate: 450,
    diagramType: "sliding_3_track",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "aluminium_sliding_door_2_track",
    label: "Aluminium sliding door — 2 Track",
    category: "aluminium",
    pricingMode: "per_sqft",
    defaultRate: 475,
    minRate: 450,
    maxRate: 500,
    diagramType: "sliding_2_track",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "aluminium_sliding_door_3_track",
    label: "Aluminium sliding door — 3 Track",
    category: "aluminium",
    pricingMode: "per_sqft",
    defaultRate: 525,
    minRate: 500,
    maxRate: 550,
    diagramType: "sliding_3_track",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "aluminium_openable_door_single",
    label: "Aluminium openable door (single)",
    category: "aluminium",
    pricingMode: "per_sqft",
    defaultRate: 525,
    minRate: 500,
    maxRate: 550,
    diagramType: "openable_door_single",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "aluminium_openable_door_double",
    label: "Aluminium openable door (double)",
    category: "aluminium",
    pricingMode: "per_sqft",
    defaultRate: 575,
    minRate: 550,
    maxRate: 600,
    diagramType: "openable_door_double",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "aluminium_partition",
    label: "Aluminium partition",
    category: "aluminium",
    pricingMode: "per_sqft",
    defaultRate: 325,
    minRate: 300,
    maxRate: 350,
    diagramType: "partition",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "aluminium_fixed_window",
    label: "Aluminium fixed window",
    category: "aluminium",
    pricingMode: "per_sqft",
    defaultRate: 275,
    minRate: 250,
    maxRate: 300,
    diagramType: "fixed",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "aluminium_ventilator",
    label: "Aluminium ventilator (without fan point)",
    category: "aluminium",
    pricingMode: "per_unit",
    defaultRate: 2100,
    minRate: 2000,
    maxRate: 2200,
    diagramType: "ventilator",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    // Priced per piece at the 2x2ft size the client quoted; a materially
    // larger opening (roughly 3x4ft or up) should be priced per_sqft
    // instead — the same "per piece up to a size, per sqft above it"
    // judgement call the trade already makes for fixed windows
    // (see fixed_window vs fixed_window_per_piece above).
    productType: "aluminium_ventilator_fan_point",
    label: "Aluminium ventilator with fan point (up to 2x2 ft)",
    category: "aluminium",
    pricingMode: "per_unit",
    defaultRate: 2900,
    minRate: 2800,
    maxRate: 3000,
    diagramType: "ventilator",
    specOptions: { profiles: ["Aluminium 1.3"], colours: ["Silver", "White", "Black"], glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },

  // ---- uPVC additions ----
  {
    productType: "sliding_door_2_5_track",
    label: "uPVC sliding door — 2.5 Track",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 380,
    minRate: 360,
    maxRate: 400,
    diagramType: "sliding_door",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "openable_door_single",
    label: "uPVC openable door (single)",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 600,
    minRate: 550,
    maxRate: 650,
    diagramType: "openable_door_single",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "openable_window_double",
    label: "uPVC openable window (double)",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 500,
    minRate: 500,
    maxRate: 600,
    diagramType: "casement",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "openable_door_double",
    label: "uPVC openable door (double)",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 650,
    minRate: 600,
    maxRate: 700,
    diagramType: "openable_door_double",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "bathroom_door_upvc_sqft",
    label: "uPVC bathroom door",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 550,
    minRate: 500,
    maxRate: 650,
    diagramType: "bathroom_door",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: [], mesh: [] },
    active: true,
  },
  {
    productType: "foldable_door_upvc",
    label: "uPVC foldable door",
    category: "door",
    pricingMode: "per_unit",
    defaultRate: 2150,
    minRate: 1800,
    maxRate: 2500,
    diagramType: "foldable_door",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },
  {
    productType: "foldable_window_upvc",
    label: "uPVC foldable window",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 2150,
    minRate: 1800,
    maxRate: 2500,
    diagramType: "foldable_window",
    specOptions: { profiles: PROFILE_OPTIONS, colours: COLOUR_OPTIONS, glass: GLASS_OPTIONS, mesh: [] },
    active: true,
  },

  // ---- mesh additions ----
  {
    productType: "mesh_pleated_nylon",
    label: "Pleated mesh (Nylon)",
    category: "mesh",
    pricingMode: "per_sqft",
    defaultRate: 300,
    minRate: 280,
    maxRate: 320,
    diagramType: "mesh_standalone",
    specOptions: { profiles: [], colours: [], glass: [], mesh: MESH_OPTIONS },
    active: true,
  },
  {
    productType: "mesh_pleated_ss",
    label: "Pleated mesh (SS)",
    category: "mesh",
    pricingMode: "per_sqft",
    defaultRate: 400,
    minRate: 380,
    maxRate: 450,
    diagramType: "mesh_standalone",
    specOptions: { profiles: [], colours: [], glass: [], mesh: MESH_OPTIONS },
    active: true,
  },

  // ---- PVC doors ----
  {
    productType: "pvc_door",
    label: "PVC door",
    category: "door",
    pricingMode: "per_unit",
    defaultRate: 2700,
    minRate: 2500,
    maxRate: 3000,
    diagramType: "flush_door",
    specOptions: { profiles: [], colours: ["White", "Teak color", "Brown"], glass: [], mesh: [] },
    active: true,
  },
  {
    productType: "pvc_door_digital",
    label: "PVC door (digital print)",
    category: "door",
    pricingMode: "per_unit",
    defaultRate: 3200,
    minRate: 3000,
    maxRate: 3500,
    diagramType: "flush_door",
    specOptions: { profiles: [], colours: [], glass: [], mesh: [] },
    active: true,
  },

  // ---- WPC additions ----
  {
    productType: "wpc_sqft",
    label: "WPC panel",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 225,
    minRate: 170,
    maxRate: 280,
    diagramType: "flush_door",
    specOptions: { profiles: ["WPC"], colours: ["Teak", "Walnut", "White"], glass: [], mesh: [] },
    active: true,
  },
  {
    productType: "wpc_door_sqft",
    label: "WPC door",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 200,
    minRate: 170,
    maxRate: 280,
    diagramType: "flush_door",
    specOptions: { profiles: ["WPC"], colours: ["Teak", "Walnut", "White"], glass: [], mesh: [] },
    active: true,
  },
  {
    productType: "wpc_frame",
    label: "WPC frame",
    category: "door",
    pricingMode: "per_sqft",
    defaultRate: 160,
    minRate: 120,
    maxRate: 160,
    diagramType: "door_frame",
    specOptions: { profiles: ["WPC"], colours: ["Teak", "Walnut", "White"], glass: [], mesh: [] },
    active: true,
  },

  // ---- glass ----
  {
    productType: "dgu_glass",
    label: "DGU glass (12–25mm)",
    category: "casement_fixed",
    pricingMode: "per_sqft",
    defaultRate: 350,
    minRate: 300,
    maxRate: 400,
    diagramType: "dgu_glass",
    specOptions: { profiles: [], colours: [], glass: ["DGU glass"], mesh: [] },
    active: true,
  },
];
